### ISSUE TITLE
Exception occur if I call the Metis/stdf2ph5.SHP inside the spyder environment

### ISSUE THREAD

**Issue by Zlin526F** [Semi-ATE/Metis#24]
Hello,
I wrote an plugin for spyder with the Metis-package. 
When I call SHP.import_stdf_into_hdf5 an exception in spyder occur:
![image](https://user-images.githubusercontent.com/75318923/155103332-37454c74-dbe9-4b72-9776-e97033ae8cbf.png)

Unfortunately I also don't get more information about what exactly goes wrong with the internal console of spyder.
But if I comment out the line with the tqdm, then it runs.
![image](https://user-images.githubusercontent.com/75318923/155104286-8dad1217-b9fd-4643-a63e-0ebd471a13de.png)

**Comment by seimit** [comment]
Hello,
I pushed the changes.
Now the SHP.import_stdf_into_hdf5  method have 2 more arguments:
disable_progress and disable_trace 
Both of them have default value False.
Setting the value to true will disable tqdm library and/or trace in the console.
Let me know if this will resolve your problem in your plugin.
Seimit
