### ISSUE TITLE
Please emit a Signal for the progress

### ISSUE THREAD

**Issue by Zlin526F** [Semi-ATE/Metis#30]
In the class stdf2ph5 is the possibility to disable the progress. I use this in a plugin for spyder, because the used tqdm Progress function generate a exception in spyder. 
But in large files, the converting to h5 takes a long time, and the user get now message, 

Could you create a Signal(int,int)  and emit this Signal in  you loop, with (progresscounter, self.records_count)?

Than I can connect to this Signal and can display this values in a own function.

**Comment by seimit** [comment]
Hello,
There is a new argument of the SHP constructor - enable_qt_update. 
By default is disabled (False). If you want to enable the new functionality, please set it with value True.
Let me know if this resolve your issue.
Regards,
Seimit
